### ISSUE TITLE
more kannel in server

### ISSUE THREAD

**Issue by csabyka** [zarplata/zabbix-agent-extension-kannel#1]
Hey

I have ~40 kannel (with different ports) in single machine, have you any idea how can i extend the monitoring for these kannels too ?

**Comment by akitsul** [comment]
Hi, 

You can create a separate host in Zabbix for each Kannel process and set the port in the {$kannel_url} macro.

Or you can add your code to discover all the kannel processes and generate the correct keys.

P.S. The module already has Low-Level Discovery of SMPP providers.
