### ISSUE TITLE
No Stats with Zabbix 4

### ISSUE THREAD

**Issue by bernddausch** [zarplata/zabbix-agent-extension-kannel#2]
Hi, 

i get only the Kennel Stat "Ok" but no Trapper Values. The Discovery has worked, but also with no Trapper Values. I can send the Values to Zabbix with the zabber_sender command.

I have set the makro for the zabbix server and the kannel url. is there some way i can check 
why the stats were not sendet

Regards,

Bernd

**Comment by tears-of-noobs** [comment]
@bernddausch Hi
Does hostname on your machine correspond with the hostname in Zabbix server?
This extension doesn't use `zabbix_sender` utility. It sends data themselves and picks up the hostname from `https://golang.org/pkg/os/#Hostname`

**Comment by bernddausch** [comment]
no the hostname was different from the hostname in the zabbix server, i have changed the hostname on the zabbix server and it worked.

thank you for your support
